import {
  Product,
  Sale,
  Inventory,
  Expense,
  Supplier,
  PurchaseOrder,
} from '../types/dataModels';

export const BUSINESS_ID = 'biz-murugan-01';

export const SEED_PRODUCTS: Product[] = [
  {
    id: 'prod-01',
    businessId: BUSINESS_ID,
    sku: 'SKU-RICE-PONNI-25',
    name: 'Ponni Boiled Rice (25kg)',
    category: 'Grains & Staples',
    unit: '25kg bag',
    purchasePrice: 920,
    sellingPrice: 1100,
    supplierId: 'sup-01',
    reorderLevel: 60,
    standardOrderQuantity: 100,
    createdAt: '2026-01-10T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z',
  },
  {
    id: 'prod-02',
    businessId: BUSINESS_ID,
    sku: 'SKU-OIL-SUN-5L',
    name: 'Gold Drop Sunflower Oil (5L)',
    category: 'Edible Oils',
    unit: '5L can',
    purchasePrice: 620,
    sellingPrice: 710,
    supplierId: 'sup-03',
    reorderLevel: 25,
    standardOrderQuantity: 50,
    createdAt: '2026-01-10T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z',
  },
  {
    id: 'prod-03',
    businessId: BUSINESS_ID,
    sku: 'SKU-DAL-TOOR-10',
    name: 'Premium Toor Dal (10kg)',
    category: 'Pulses',
    unit: '10kg bag',
    purchasePrice: 1350,
    sellingPrice: 1520,
    supplierId: 'sup-01',
    reorderLevel: 20,
    standardOrderQuantity: 25,
    createdAt: '2026-01-10T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z',
  },
  {
    id: 'prod-04',
    businessId: BUSINESS_ID,
    sku: 'SKU-SPICE-SAMBAR-500',
    name: 'Aachi Sambar Powder (500g)',
    category: 'Spices & Masalas',
    unit: '500g pack',
    purchasePrice: 140,
    sellingPrice: 175,
    supplierId: 'sup-02',
    reorderLevel: 30,
    standardOrderQuantity: 60,
    createdAt: '2026-01-10T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z',
  },
  {
    id: 'prod-05',
    businessId: BUSINESS_ID,
    sku: 'SKU-RICE-SONA-25',
    name: 'Sona Masoori Rice (25kg)',
    category: 'Grains & Staples',
    unit: '25kg bag',
    purchasePrice: 1050,
    sellingPrice: 1250,
    supplierId: 'sup-01',
    reorderLevel: 35,
    standardOrderQuantity: 50,
    createdAt: '2026-01-10T00:00:00Z',
    updatedAt: '2026-09-01T00:00:00Z',
  },
];

export const SEED_SUPPLIERS: Supplier[] = [
  {
    id: 'sup-01',
    businessId: BUSINESS_ID,
    name: 'Kaveri Wholesale Grain Traders',
    contactPerson: 'S. Sundaram',
    phone: '+91 94440 88219',
    email: 'orders@kaveritraders.in',
    leadTimeDays: 3,
    productsSupplied: ['Ponni Boiled Rice (25kg)', 'Sona Masoori Rice (25kg)', 'Toor Dal (10kg)'],
  },
  {
    id: 'sup-02',
    businessId: BUSINESS_ID,
    name: 'Madras Spices & Condiments Ltd',
    contactPerson: 'K. Balaji',
    phone: '+91 98842 11980',
    email: 'supply@madrasspices.com',
    leadTimeDays: 2,
    productsSupplied: ['Sambar Powder (500g)', 'Turmeric Powder (500g)', 'Black Pepper (1kg)'],
  },
  {
    id: 'sup-03',
    businessId: BUSINESS_ID,
    name: 'Gold Harvest Edible Oils Depot',
    contactPerson: 'M. Ramanathan',
    phone: '+91 97910 44520',
    email: 'raman@goldharvestoils.com',
    leadTimeDays: 2,
    productsSupplied: ['Sunflower Oil (5L Can)', 'Gingelly Oil (1L)', 'Groundnut Oil (5L)'],
  },
];

export const SEED_INVENTORY: Inventory[] = [
  {
    id: 'inv-01',
    businessId: BUSINESS_ID,
    productId: 'SKU-RICE-PONNI-25',
    productName: 'Ponni Boiled Rice (25kg)',
    category: 'Grains & Staples',
    currentStock: 95,
    reorderLevel: 60,
    purchasePrice: 920,
    sellingPrice: 1100,
    supplierId: 'sup-01',
    supplierName: 'Kaveri Wholesale Grain Traders',
    salesVelocityUnitsPerWeek: 12,
    previousSalesVelocityUnitsPerWeek: 20, // 40% drop
    stockStatus: 'overstocked',
    lastRestockedDate: '2026-09-03',
    updatedAt: '2026-09-30T00:00:00Z',
  },
  {
    id: 'inv-02',
    businessId: BUSINESS_ID,
    productId: 'SKU-OIL-SUN-5L',
    productName: 'Gold Drop Sunflower Oil (5L)',
    category: 'Edible Oils',
    currentStock: 34,
    reorderLevel: 25,
    purchasePrice: 620,
    sellingPrice: 710,
    supplierId: 'sup-03',
    supplierName: 'Gold Harvest Edible Oils Depot',
    salesVelocityUnitsPerWeek: 18,
    previousSalesVelocityUnitsPerWeek: 19,
    stockStatus: 'optimal',
    lastRestockedDate: '2026-09-12',
    updatedAt: '2026-09-30T00:00:00Z',
  },
  {
    id: 'inv-03',
    businessId: BUSINESS_ID,
    productId: 'SKU-DAL-TOOR-10',
    productName: 'Premium Toor Dal (10kg)',
    category: 'Pulses',
    currentStock: 18, // < reorderLevel 20 -> LOW STOCK!
    reorderLevel: 20,
    purchasePrice: 1350,
    sellingPrice: 1520,
    supplierId: 'sup-01',
    supplierName: 'Kaveri Wholesale Grain Traders',
    salesVelocityUnitsPerWeek: 15,
    previousSalesVelocityUnitsPerWeek: 14,
    stockStatus: 'low',
    lastRestockedDate: '2026-08-28',
    updatedAt: '2026-09-30T00:00:00Z',
  },
  {
    id: 'inv-04',
    businessId: BUSINESS_ID,
    productId: 'SKU-SPICE-SAMBAR-500',
    productName: 'Aachi Sambar Powder (500g)',
    category: 'Spices & Masalas',
    currentStock: 45,
    reorderLevel: 30,
    purchasePrice: 140,
    sellingPrice: 175,
    supplierId: 'sup-02',
    supplierName: 'Madras Spices & Condiments Ltd',
    salesVelocityUnitsPerWeek: 22,
    previousSalesVelocityUnitsPerWeek: 24,
    stockStatus: 'optimal',
    lastRestockedDate: '2026-09-15',
    updatedAt: '2026-09-30T00:00:00Z',
  },
  {
    id: 'inv-05',
    businessId: BUSINESS_ID,
    productId: 'SKU-RICE-SONA-25',
    productName: 'Sona Masoori Rice (25kg)',
    category: 'Grains & Staples',
    currentStock: 42,
    reorderLevel: 35,
    purchasePrice: 1050,
    sellingPrice: 1250,
    supplierId: 'sup-01',
    supplierName: 'Kaveri Wholesale Grain Traders',
    salesVelocityUnitsPerWeek: 16,
    previousSalesVelocityUnitsPerWeek: 15,
    stockStatus: 'optimal',
    lastRestockedDate: '2026-09-08',
    updatedAt: '2026-09-30T00:00:00Z',
  },
];

export const SEED_SALES: Sale[] = [
  // Current Period Sales (Sep 2026) -> Total = ₹1,42,800
  {
    id: 'sale-c-01',
    businessId: BUSINESS_ID,
    date: '2026-09-04',
    productId: 'SKU-RICE-PONNI-25',
    productName: 'Ponni Boiled Rice (25kg)',
    category: 'Grains & Staples',
    quantity: 48,
    unitPrice: 1100,
    totalRevenue: 52800,
    period: 'current',
  },
  {
    id: 'sale-c-02',
    businessId: BUSINESS_ID,
    date: '2026-09-10',
    productId: 'SKU-OIL-SUN-5L',
    productName: 'Gold Drop Sunflower Oil (5L)',
    category: 'Edible Oils',
    quantity: 68,
    unitPrice: 710,
    totalRevenue: 48280,
    period: 'current',
  },
  {
    id: 'sale-c-03',
    businessId: BUSINESS_ID,
    date: '2026-09-17',
    productId: 'SKU-DAL-TOOR-10',
    productName: 'Premium Toor Dal (10kg)',
    category: 'Pulses',
    quantity: 16,
    unitPrice: 1520,
    totalRevenue: 24320,
    period: 'current',
  },
  {
    id: 'sale-c-04',
    businessId: BUSINESS_ID,
    date: '2026-09-24',
    productId: 'SKU-SPICE-SAMBAR-500',
    productName: 'Aachi Sambar Powder (500g)',
    category: 'Spices & Masalas',
    quantity: 100,
    unitPrice: 174,
    totalRevenue: 17400,
    period: 'current',
  },

  // Previous Period Sales (Aug 2026) -> Total = ₹1,42,500
  {
    id: 'sale-p-01',
    businessId: BUSINESS_ID,
    date: '2026-08-04',
    productId: 'SKU-RICE-PONNI-25',
    productName: 'Ponni Boiled Rice (25kg)',
    category: 'Grains & Staples',
    quantity: 80,
    unitPrice: 1100,
    totalRevenue: 88000,
    period: 'previous',
  },
  {
    id: 'sale-p-02',
    businessId: BUSINESS_ID,
    date: '2026-08-10',
    productId: 'SKU-OIL-SUN-5L',
    productName: 'Gold Drop Sunflower Oil (5L)',
    category: 'Edible Oils',
    quantity: 45,
    unitPrice: 710,
    totalRevenue: 31950,
    period: 'previous',
  },
  {
    id: 'sale-p-03',
    businessId: BUSINESS_ID,
    date: '2026-08-17',
    productId: 'SKU-DAL-TOOR-10',
    productName: 'Premium Toor Dal (10kg)',
    category: 'Pulses',
    quantity: 10,
    unitPrice: 1520,
    totalRevenue: 15200,
    period: 'previous',
  },
  {
    id: 'sale-p-04',
    businessId: BUSINESS_ID,
    date: '2026-08-24',
    productId: 'SKU-SPICE-SAMBAR-500',
    productName: 'Aachi Sambar Powder (500g)',
    category: 'Spices & Masalas',
    quantity: 42,
    unitPrice: 175,
    totalRevenue: 7350,
    period: 'previous',
  },
];

export const SEED_EXPENSES: Expense[] = [
  // Current Period (Sep 2026) - Total = ₹94,100
  // Note: Operating Profit Current = 1,42,800 - 94,100 = ₹48,700
  {
    id: 'exp-c-01',
    businessId: BUSINESS_ID,
    date: '2026-09-08',
    category: 'Purchase Cost',
    amount: 68500, // +15,500 increase vs 53,000
    period: 'current',
    notes: 'Bulk stock replenishment including 100 bags Ponni rice',
  },
  {
    id: 'exp-c-02',
    businessId: BUSINESS_ID,
    date: '2026-09-12',
    category: 'Wastage',
    amount: 5400, // +3,200 increase vs 2,200
    period: 'current',
    notes: 'Moisture spoilage & damaged sacks in damp storage area',
  },
  {
    id: 'exp-c-03',
    businessId: BUSINESS_ID,
    date: '2026-09-15',
    category: 'Delivery Expense',
    amount: 4320, // +1,720 increase vs 2,600
    period: 'current',
    notes: 'Rush tempo freight and offloading demurrage fee',
  },
  {
    id: 'exp-c-04',
    businessId: BUSINESS_ID,
    date: '2026-09-25',
    category: 'Rent',
    amount: 10000,
    period: 'current',
    notes: 'Shop lease T. Nagar portion',
  },
  {
    id: 'exp-c-05',
    businessId: BUSINESS_ID,
    date: '2026-09-27',
    category: 'Electricity',
    amount: 3500,
    period: 'current',
    notes: 'TNEB commercial tariff',
  },
  {
    id: 'exp-c-06',
    businessId: BUSINESS_ID,
    date: '2026-09-28',
    category: 'Packaging',
    amount: 2380,
    period: 'current',
    notes: 'Carry bags and gunny packing',
  },

  // Previous Period (Aug 2026) - Total = ₹85,380
  // Note: Operating Profit Previous = 1,42,500 - 85,380 = ₹57,120
  // Profit Delta = 48,700 - 57,120 = -₹8,420 exactly!
  {
    id: 'exp-p-01',
    businessId: BUSINESS_ID,
    date: '2026-08-08',
    category: 'Purchase Cost',
    amount: 53000,
    period: 'previous',
    notes: 'Routine scheduled procurement',
  },
  {
    id: 'exp-p-02',
    businessId: BUSINESS_ID,
    date: '2026-08-12',
    category: 'Wastage',
    amount: 2200,
    period: 'previous',
    notes: 'Normal incidental handling wastage',
  },
  {
    id: 'exp-p-03',
    businessId: BUSINESS_ID,
    date: '2026-08-15',
    category: 'Delivery Expense',
    amount: 2600,
    period: 'previous',
    notes: 'Regular freight van shipment',
  },
  {
    id: 'exp-p-04',
    businessId: BUSINESS_ID,
    date: '2026-08-25',
    category: 'Rent',
    amount: 10000,
    period: 'previous',
    notes: 'Shop lease T. Nagar portion',
  },
  {
    id: 'exp-p-05',
    businessId: BUSINESS_ID,
    date: '2026-08-27',
    category: 'Electricity',
    amount: 3500,
    period: 'previous',
    notes: 'TNEB commercial tariff',
  },
  {
    id: 'exp-p-06',
    businessId: BUSINESS_ID,
    date: '2026-08-28',
    category: 'Packaging',
    amount: 3580,
    period: 'previous',
    notes: 'Gunny bags and twine rolls',
  },
  {
    id: 'exp-p-07',
    businessId: BUSINESS_ID,
    date: '2026-08-29',
    category: 'Other',
    amount: 10500,
    period: 'previous',
    notes: 'Annual trade license renewal & premise fumigation (one-off previous expense)',
  },
];

export const SEED_PURCHASE_ORDERS: PurchaseOrder[] = [];
